version: '3.1'

services:
  # Add your host volumen in path/to/... or add your own volume below
  mpd:
    build:
      context: mpd/
    image: alpine-mpd:custom
    depends_on:
      - icecast
    networks:
      - music_stack
    volumes:
      - mpd_music:/var/lib/mpd/music
      - mpd_playlists:/var/lib/mpd/playlists
      - mpd_database:/var/lib/mpd/database

#  sima:
#    build:
#      context: sima/
#    image: alpine-sima:custom
#    depends_on:
#      - mpd
#    networks:
#      - music_stack

  ympd:
    build:
      context: ympd/
    image: alpine-ympd:custom
    depends_on:
      - mpd
    networks:
      - music_stack
    restart: unless-stopped

  caddy:
    image: caddy/caddy:latest
    ports:
      - "8081:8081"
      - "8000:8000"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - mpd
    networks:
      - music_stack
      - public_network
    restart: unless-stopped

  file_browser:
    image: filebrowser/filebrowser:latest
    volumes:
      - filebrowser_db:/database
      - mpd_music:/srv/scream/mpd_music
      - recorder_uploads:/srv/scream/recorder_uploads
      - ./file-browser/settings.json:/.filebrowser.json
    networks:
      - music_stack
    restart: unless-stopped

  icecast:
    build:
      context: icecast/
    image: alpine-icecast:custom
    networks:
      - music_stack
    restart: unless-stopped

  ssh-upload-server:
    build:
      context: ssh-upload-server/
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - PUBLIC_KEY_FILE=/id_rsa.pub
      - PUBLIC_KEY_URL=https://github.com/radist2s.keys
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=false
      - USER_PASSWORD=recorder
      - USER_NAME=recorder
    volumes:
      - ./ssh-upload-server/id_rsa.pub:/id_rsa.pub
      - recorder_uploads:/recorder_uploads
    ports:
      - "2222:2222"
    restart: unless-stopped
    networks:
      - public_network
  frps:
    image: fatedier/frp:latest
    volumes:
      - ./frps/frps.ini:/frps.ini
    command: ["/usr/bin/frps", "-c", "/frps.ini"]

networks:
  music_stack:
  public_network:
    driver: bridge

volumes:
  mpd_playlists:
    external: true
  mpd_database:
    external: true
  mpd_music:
    external: true
  filebrowser_db:
  recorder_uploads:
    external: true

